### PR TITLE
fix corner arrow integration

### PR DESCRIPTION
**Pull request by gautierdelorme**
fix corner arrow integration with popover corner radius.
fix this :  to this

### CODE REVIEW

**Comment by corin8823** [comment]
Hi @gautierdelorme 
Thanks PR! 
Sorry, wasn't able to merge without conflicts so I just merge the other branch.
I want to merge your branch, so I want to you to align the format of my code?

**Comment by gautierdelorme** [comment]
Hi @corin8823 ! Problem is your code is not well indented so I corrected that.
To fix the conflict go to your file in XCode cmd+a to select all the code, then ctrl+i to re-indent it well.
And then you will be able to merge my PR without any issue.

**Comment by corin8823** [comment]
Hi @gautierdelorme !
Indent of my code is 2space because according to the [swift-style-guide](https://github.com/raywenderlich/swift-style-guide#spacing).
Please be close If you do not have mind to fix.
Thank you PR!

**Comment by gautierdelorme** [comment]
Hi @corin8823 !
No problem, everything should be fine now. :)

**Comment by corin8823** [comment]
Thanks for your work!! :+1:

**Pull request merged**
