### PR TITLE
Show content view as a dialog

### PR DESCRIPTION
**Pull request by kientux**
Add methods to show `contentView` as a dialog in center of `inView`.

### CODE REVIEW

**Comment by corin8823** [comment]
Thanks PR! I'd like to ask a one question.
What kind of image do you use for UI?

**Comment by kientux** [comment]
I don't think I understand the question. What do you mean by saying "image"? :D

**Comment by corin8823** [comment]
Sorry. "image" mean "use case" :)

**Comment by kientux** [comment]
Oh. I use this when I want to show a `UIView` with the same animation and appearance as `Popover`, but without any arrow point :D Just like a `UIAlertView` or `UIAlertController`.

**Comment by corin8823** [comment]
OK! I understand that your PR
Thanks PR. Thanks use this library.

**Pull request merged**
